#!/bin/sh -e
redo-ifchange ./ar ./arflags
read ar < ./ar
read arflags < ./arflags
archive="$1"
shift
rm -f -- "$archive"
#echo "${ar}" ${arflags} "$archive" "$@" 1>&2
"${ar}" ${arflags} "$archive" "$@"
