#!/bin/sh -e
if [ \! -d package -o \! -d source ] 
then
	echo "You are not in the right directory." 1>&2 
	exit 100
fi

cd build
if [ "`uname`" = "Interix" ]
then
	echo wlib.exe > ar
	echo -n -q > arflags
else
	echo ar > ar
	echo rc > arflags
fi
if type >/dev/null clang++
then
	echo clang++ > cxx
	echo > cppflags
	echo -g -Wall -Wextra -integrated-as > cxxflags
	echo -g > ldflags
elif type >/dev/null g++
then
	echo g++ > cxx
	echo > cppflags
	echo -g -Wall -Wextra > cxxflags
	echo -g > ldflags
elif type >/dev/null owcc
then
	echo owcc > cxx
	echo > cppflags
	echo -g -Wall -Wextra -Wc,-xs -Wc,-xr > cxxflags
	echo -g > ldflags
elif type >/dev/null owcc.exe
then
	echo owcc.exe > cxx
	echo > cppflags
	echo -g -Wall -Wextra -Wc,-xs -Wc,-xr > cxxflags
	echo -g > ldflags
else
	echo "Cannot find clang++, g++, or owcc." 1>&2
	false
fi
